// Mocks generated by Mockito from annotations
// in onebit/test/ble_service_channel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:onebit/features/ble/ble_service.dart' as _i3;
import 'package:onebit/features/ble/ble_state.dart' as _i2;
import 'package:onebit/features/ble/ble_uuids.dart' as _i7;
import 'package:onebit/features/ble/discovered_device.dart' as _i5;
import 'package:onebit/features/reliable/transfer.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBleState_0 extends _i1.SmartFake implements _i2.BleState {
  _FakeBleState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleConnectionInfo_1 extends _i1.SmartFake
    implements _i2.BleConnectionInfo {
  _FakeBleConnectionInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleService extends _i1.Mock implements _i3.BleService {
  MockBleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BleState get current => (super.noSuchMethod(
    Invocation.getter(#current),
    returnValue: _FakeBleState_0(this, Invocation.getter(#current)),
  ) as _i2.BleState);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  _i4.Stream<_i2.BleState> get stateStream => (super.noSuchMethod(
    Invocation.getter(#stateStream),
    returnValue: _i4.Stream<_i2.BleState>.empty(),
  ) as _i4.Stream<_i2.BleState>);

  @override
  List<_i5.DiscoveredOneBitDevice> get devices => (super.noSuchMethod(
    Invocation.getter(#devices),
    returnValue: <_i5.DiscoveredOneBitDevice>[],
  ) as List<_i5.DiscoveredOneBitDevice>);

  @override
  _i4.Stream<_i5.DiscoveredOneBitDevice> get discoveryStream =>
      (super.noSuchMethod(
        Invocation.getter(#discoveryStream),
        returnValue: _i4.Stream<_i5.DiscoveredOneBitDevice>.empty(),
      ) as _i4.Stream<_i5.DiscoveredOneBitDevice>);

  @override
  _i4.Stream<_i2.BleCharacteristicValue> get characteristicChanged =>
      (super.noSuchMethod(
        Invocation.getter(#characteristicChanged),
        returnValue: _i4.Stream<_i2.BleCharacteristicValue>.empty(),
      ) as _i4.Stream<_i2.BleCharacteristicValue>);

  @override
  _i4.Stream<_i2.ReliableDataReceived> get reliableDataReceived =>
      (super.noSuchMethod(
        Invocation.getter(#reliableDataReceived),
        returnValue: _i4.Stream<_i2.ReliableDataReceived>.empty(),
      ) as _i4.Stream<_i2.ReliableDataReceived>);

  @override
  _i4.Future<_i6.TransferResult> sendReliable(
    String? deviceId,
    List<int>? payload,
  ) => (super.noSuchMethod(
    Invocation.method(#sendReliable, [deviceId, payload]),
    returnValue: _i4.Future<_i6.TransferResult>.value(
      _i6.TransferResult.delivered,
    ),
  ) as _i4.Future<_i6.TransferResult>);

  @override
  void pushDiscovery(_i5.DiscoveredOneBitDevice? device) => super.noSuchMethod(
    Invocation.method(#pushDiscovery, [device]),
    returnValueForMissingStub: null,
  );

  @override
  void pushConnectionState(String? deviceId, _i2.BleConnectionState? state) =>
      super.noSuchMethod(
        Invocation.method(#pushConnectionState, [deviceId, state]),
        returnValueForMissingStub: null,
      );

  @override
  void pushCharacteristicChanged({
    required String? deviceId,
    required String? serviceUuid,
    required String? characteristicUuid,
    required List<int>? value,
    bool? isIndication = false,
  }) => super.noSuchMethod(
    Invocation.method(#pushCharacteristicChanged, [], {
      #deviceId: deviceId,
      #serviceUuid: serviceUuid,
      #characteristicUuid: characteristicUuid,
      #value: value,
      #isIndication: isIndication,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.BlePermissionState> requestPermissions() =>
      (super.noSuchMethod(
        Invocation.method(#requestPermissions, []),
        returnValue: _i4.Future<_i2.BlePermissionState>.value(
          _i2.BlePermissionState.granted,
        ),
      ) as _i4.Future<_i2.BlePermissionState>);

  @override
  _i4.Future<_i2.BlePermissionState> recoverPermissions() =>
      (super.noSuchMethod(
        Invocation.method(#recoverPermissions, []),
        returnValue: _i4.Future<_i2.BlePermissionState>.value(
          _i2.BlePermissionState.granted,
        ),
      ) as _i4.Future<_i2.BlePermissionState>);

  @override
  _i4.Future<void> openBluetoothSettings() => (super.noSuchMethod(
    Invocation.method(#openBluetoothSettings, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<String> startAdvertising(_i7.BleAdvertiseConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(#startAdvertising, [config]),
        returnValue: _i4.Future<String>.value(
          _i8.dummyValue<String>(
            this,
            Invocation.method(#startAdvertising, [config]),
          ),
        ),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> stopAdvertising() => (super.noSuchMethod(
    Invocation.method(#stopAdvertising, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<String> startScan(_i2.BleScanConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(#startScan, [config]),
        returnValue: _i4.Future<String>.value(
          _i8.dummyValue<String>(this, Invocation.method(#startScan, [config])),
        ),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> stopScan() => (super.noSuchMethod(
    Invocation.method(#stopScan, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.BleConnectionInfo> connect(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(#connect, [deviceId]),
        returnValue: _i4.Future<_i2.BleConnectionInfo>.value(
          _FakeBleConnectionInfo_1(
            this,
            Invocation.method(#connect, [deviceId]),
          ),
        ),
      ) as _i4.Future<_i2.BleConnectionInfo>);

  @override
  _i4.Future<void> disconnect(String? deviceId) => (super.noSuchMethod(
    Invocation.method(#disconnect, [deviceId]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> discoverServices(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(#discoverServices, [deviceId]),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<int>> readCharacteristic(
    String? deviceId,
    String? serviceUuid,
    String? characteristicUuid,
  ) => (super.noSuchMethod(
    Invocation.method(#readCharacteristic, [
      deviceId,
      serviceUuid,
      characteristicUuid,
    ]),
    returnValue: _i4.Future<List<int>>.value(<int>[]),
  ) as _i4.Future<List<int>>);

  @override
  _i4.Future<void> writeCharacteristic(
    String? deviceId,
    String? serviceUuid,
    String? characteristicUuid,
    List<int>? value, {
    bool? withoutResponse = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #writeCharacteristic,
      [deviceId, serviceUuid, characteristicUuid, value],
      {#withoutResponse: withoutResponse},
    ),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> setNotify(
    String? deviceId,
    String? serviceUuid,
    String? characteristicUuid,
    bool? enabled,
  ) => (super.noSuchMethod(
    Invocation.method(#setNotify, [
      deviceId,
      serviceUuid,
      characteristicUuid,
      enabled,
    ]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}
