// Mocks generated by Mockito from annotations
// in onebit/test/identity_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:onebit/features/identity/identity_export.dart' as _i7;
import 'package:onebit/features/identity/identity_models.dart' as _i2;
import 'package:onebit/features/identity/identity_repository.dart' as _i3;
import 'package:onebit/features/identity/private_key_store.dart' as _i8;
import 'package:onebit/features/trust/peer_trust.dart' as _i5;
import 'package:onebit/features/trust/trust_state.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIdentityInfo_0 extends _i1.SmartFake implements _i2.IdentityInfo {
  _FakeIdentityInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IdentityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdentityRepository extends _i1.Mock
    implements _i3.IdentityRepository {
  MockIdentityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.IdentityInfo?> getLocalIdentity() => (super.noSuchMethod(
    Invocation.method(#getLocalIdentity, []),
    returnValue: _i4.Future<_i2.IdentityInfo?>.value(),
  ) as _i4.Future<_i2.IdentityInfo?>);

  @override
  _i4.Future<_i2.IdentityInfo> createLocalIdentity({
    required String? displayName,
    String? publicKeyHex,
  }) => (super.noSuchMethod(
    Invocation.method(#createLocalIdentity, [], {
      #displayName: displayName,
      #publicKeyHex: publicKeyHex,
    }),
    returnValue: _i4.Future<_i2.IdentityInfo>.value(
      _FakeIdentityInfo_0(
        this,
        Invocation.method(#createLocalIdentity, [], {
          #displayName: displayName,
          #publicKeyHex: publicKeyHex,
        }),
      ),
    ),
  ) as _i4.Future<_i2.IdentityInfo>);

  @override
  _i4.Future<void> updateLocalIdentityCrypto({
    required int? id,
    required String? identityId,
    required String? publicKeyHex,
  }) => (super.noSuchMethod(
    Invocation.method(#updateLocalIdentityCrypto, [], {
      #id: id,
      #identityId: identityId,
      #publicKeyHex: publicKeyHex,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLocalIdentityProfile({
    required int? id,
    required String? displayName,
    String? about,
  }) => (super.noSuchMethod(
    Invocation.method(#updateLocalIdentityProfile, [], {
      #id: id,
      #displayName: displayName,
      #about: about,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.PeerInfo?> getPeerIdentity(int? id) => (super.noSuchMethod(
    Invocation.method(#getPeerIdentity, [id]),
    returnValue: _i4.Future<_i2.PeerInfo?>.value(),
  ) as _i4.Future<_i2.PeerInfo?>);

  @override
  _i4.Future<List<_i2.PeerInfo>> getAllPeerIdentities() => (super.noSuchMethod(
    Invocation.method(#getAllPeerIdentities, []),
    returnValue: _i4.Future<List<_i2.PeerInfo>>.value(<_i2.PeerInfo>[]),
  ) as _i4.Future<List<_i2.PeerInfo>>);

  @override
  _i4.Future<List<_i2.PeerInfo>> getAllPeers() => (super.noSuchMethod(
    Invocation.method(#getAllPeers, []),
    returnValue: _i4.Future<List<_i2.PeerInfo>>.value(<_i2.PeerInfo>[]),
  ) as _i4.Future<List<_i2.PeerInfo>>);

  @override
  _i4.Stream<List<_i2.PeerInfo>> watchPeerIdentities() => (super.noSuchMethod(
    Invocation.method(#watchPeerIdentities, []),
    returnValue: _i4.Stream<List<_i2.PeerInfo>>.empty(),
  ) as _i4.Stream<List<_i2.PeerInfo>>);

  @override
  _i4.Future<void> upsertPeerIdentity({
    required String? displayName,
    required DateTime? createdAt,
    String? identityId,
    String? publicKeyHex,
    DateTime? lastSeenAt,
    String? keyAgreementPublicKeyHex,
  }) => (super.noSuchMethod(
    Invocation.method(#upsertPeerIdentity, [], {
      #displayName: displayName,
      #createdAt: createdAt,
      #identityId: identityId,
      #publicKeyHex: publicKeyHex,
      #lastSeenAt: lastSeenAt,
      #keyAgreementPublicKeyHex: keyAgreementPublicKeyHex,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<int> deletePeerIdentity(int? id) => (super.noSuchMethod(
    Invocation.method(#deletePeerIdentity, [id]),
    returnValue: _i4.Future<int>.value(0),
  ) as _i4.Future<int>);

  @override
  _i4.Future<void> renamePeer({required int? id, required String? newName}) =>
      (super.noSuchMethod(
        Invocation.method(#renamePeer, [], {#id: id, #newName: newName}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePeerKeyAgreementPublicKey({
    required int? id,
    required String? keyAgreementPublicKeyHex,
  }) => (super.noSuchMethod(
    Invocation.method(#updatePeerKeyAgreementPublicKey, [], {
      #id: id,
      #keyAgreementPublicKeyHex: keyAgreementPublicKeyHex,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePeerLastSeenBleAddress({
    required int? id,
    required String? lastSeenBleAddress,
  }) => (super.noSuchMethod(
    Invocation.method(#updatePeerLastSeenBleAddress, [], {
      #id: id,
      #lastSeenBleAddress: lastSeenBleAddress,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<int> removePeer(int? id) => (super.noSuchMethod(
    Invocation.method(#removePeer, [id]),
    returnValue: _i4.Future<int>.value(0),
  ) as _i4.Future<int>);

  @override
  _i4.Future<_i2.PeerInfo?> getPeerByIdentityId(String? identityId) =>
      (super.noSuchMethod(
        Invocation.method(#getPeerByIdentityId, [identityId]),
        returnValue: _i4.Future<_i2.PeerInfo?>.value(),
      ) as _i4.Future<_i2.PeerInfo?>);

  @override
  _i4.Future<List<_i5.PeerTrust>> loadAllTrust() => (super.noSuchMethod(
    Invocation.method(#loadAllTrust, []),
    returnValue: _i4.Future<List<_i5.PeerTrust>>.value(<_i5.PeerTrust>[]),
  ) as _i4.Future<List<_i5.PeerTrust>>);

  @override
  _i4.Future<void> savePeerTrust({
    required String? peerIdentityId,
    required _i6.TrustState? state,
    DateTime? verifiedAt,
    _i5.VerificationMethod? verificationMethod,
    DateTime? trustedAt,
  }) => (super.noSuchMethod(
    Invocation.method(#savePeerTrust, [], {
      #peerIdentityId: peerIdentityId,
      #state: state,
      #verifiedAt: verifiedAt,
      #verificationMethod: verificationMethod,
      #trustedAt: trustedAt,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<(_i2.PeerInfo?, _i3.AssociationResult)> findOrCreatePeer({
    required _i7.PublicIdentity? publicIdentity,
    required String? localPublicKeyHex,
    String? keyAgreementPublicKeyHex,
  }) => (super.noSuchMethod(
    Invocation.method(#findOrCreatePeer, [], {
      #publicIdentity: publicIdentity,
      #localPublicKeyHex: localPublicKeyHex,
      #keyAgreementPublicKeyHex: keyAgreementPublicKeyHex,
    }),
    returnValue: _i4.Future<(_i2.PeerInfo?, _i3.AssociationResult)>.value((
      null,
      _i3.AssociationResult.created,
    )),
  ) as _i4.Future<(_i2.PeerInfo?, _i3.AssociationResult)>);
}

/// A class which mocks [PrivateKeyStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrivateKeyStore extends _i1.Mock implements _i8.PrivateKeyStore {
  MockPrivateKeyStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.Uint8List?> read() => (super.noSuchMethod(
    Invocation.method(#read, []),
    returnValue: _i4.Future<_i9.Uint8List?>.value(),
  ) as _i4.Future<_i9.Uint8List?>);

  @override
  _i4.Future<void> write(_i9.Uint8List? keyBytes) => (super.noSuchMethod(
    Invocation.method(#write, [keyBytes]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete() => (super.noSuchMethod(
    Invocation.method(#delete, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}
