// Mocks generated by Mockito from annotations
// in onebit/test/multi_peer_routing_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:onebit/features/peer_registry/peer_association.dart' as _i4;
import 'package:onebit/features/peer_registry/peer_connection_manager.dart'
    as _i2;
import 'package:onebit/features/peer_registry/peer_lifecycle_state.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PeerConnectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerConnectionManager extends _i1.Mock
    implements _i2.PeerConnectionManager {
  MockPeerConnectionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i2.PeerConnectionRecord>> get connectionStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStream),
        returnValue: _i3.Stream<List<_i2.PeerConnectionRecord>>.empty(),
      ) as _i3.Stream<List<_i2.PeerConnectionRecord>>);

  @override
  List<_i2.PeerConnectionRecord> get connections => (super.noSuchMethod(
    Invocation.getter(#connections),
    returnValue: <_i2.PeerConnectionRecord>[],
  ) as List<_i2.PeerConnectionRecord>);

  @override
  int get connectedPeerCount => (super.noSuchMethod(
    Invocation.getter(#connectedPeerCount),
    returnValue: 0,
  ) as int);

  @override
  bool get hasActiveConnections => (super.noSuchMethod(
    Invocation.getter(#hasActiveConnections),
    returnValue: false,
  ) as bool);

  @override
  List<_i4.PeerAssociation> get currentAssociations => (super.noSuchMethod(
    Invocation.getter(#currentAssociations),
    returnValue: <_i4.PeerAssociation>[],
  ) as List<_i4.PeerAssociation>);

  @override
  int get trackedPeerCount =>
      (super.noSuchMethod(Invocation.getter(#trackedPeerCount), returnValue: 0)
          as int);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<String?> connectToPeer(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#connectToPeer, [peerIdentityId]),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> disconnectFromPeer(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#disconnectFromPeer, [peerIdentityId]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i5.PeerLifecycleState lifecycleStateFor(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#lifecycleStateFor, [peerIdentityId]),
        returnValue: _i5.PeerLifecycleState.unknown,
      ) as _i5.PeerLifecycleState);

  @override
  String? deviceForPeer(String? peerIdentityId) =>
      (super.noSuchMethod(Invocation.method(#deviceForPeer, [peerIdentityId]))
          as String?);

  @override
  bool isPeerConnected(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#isPeerConnected, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  _i3.Future<void> disconnectAll() => (super.noSuchMethod(
    Invocation.method(#disconnectAll, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
