// Mocks generated by Mockito from annotations
// in onebit/test/peer_lifecycle_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:onebit/features/ble/ble_service.dart' as _i4;
import 'package:onebit/features/ble/ble_state.dart' as _i2;
import 'package:onebit/features/ble/ble_uuids.dart' as _i8;
import 'package:onebit/features/ble/discovered_device.dart' as _i6;
import 'package:onebit/features/identity/identity_association_resolver.dart'
    as _i3;
import 'package:onebit/features/identity/identity_models.dart' as _i11;
import 'package:onebit/features/peer_registry/peer_association.dart' as _i10;
import 'package:onebit/features/peer_registry/peer_entry.dart' as _i13;
import 'package:onebit/features/peer_registry/peer_lifecycle_state.dart'
    as _i14;
import 'package:onebit/features/peer_registry/peer_registry.dart' as _i12;
import 'package:onebit/features/reliable/transfer.dart' as _i7;
import 'package:onebit/features/trust/trust_state.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBleState_0 extends _i1.SmartFake implements _i2.BleState {
  _FakeBleState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleConnectionInfo_1 extends _i1.SmartFake
    implements _i2.BleConnectionInfo {
  _FakeBleConnectionInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResolvedBleDevice_2 extends _i1.SmartFake
    implements _i3.ResolvedBleDevice {
  _FakeResolvedBleDevice_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleService extends _i1.Mock implements _i4.BleService {
  MockBleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BleState get current => (super.noSuchMethod(
    Invocation.getter(#current),
    returnValue: _FakeBleState_0(this, Invocation.getter(#current)),
  ) as _i2.BleState);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  _i5.Stream<_i2.BleState> get stateStream => (super.noSuchMethod(
    Invocation.getter(#stateStream),
    returnValue: _i5.Stream<_i2.BleState>.empty(),
  ) as _i5.Stream<_i2.BleState>);

  @override
  List<_i6.DiscoveredOneBitDevice> get devices => (super.noSuchMethod(
    Invocation.getter(#devices),
    returnValue: <_i6.DiscoveredOneBitDevice>[],
  ) as List<_i6.DiscoveredOneBitDevice>);

  @override
  _i5.Stream<_i6.DiscoveredOneBitDevice> get discoveryStream =>
      (super.noSuchMethod(
        Invocation.getter(#discoveryStream),
        returnValue: _i5.Stream<_i6.DiscoveredOneBitDevice>.empty(),
      ) as _i5.Stream<_i6.DiscoveredOneBitDevice>);

  @override
  _i5.Stream<_i2.BleCharacteristicValue> get characteristicChanged =>
      (super.noSuchMethod(
        Invocation.getter(#characteristicChanged),
        returnValue: _i5.Stream<_i2.BleCharacteristicValue>.empty(),
      ) as _i5.Stream<_i2.BleCharacteristicValue>);

  @override
  _i5.Stream<_i2.ReliableDataReceived> get reliableDataReceived =>
      (super.noSuchMethod(
        Invocation.getter(#reliableDataReceived),
        returnValue: _i5.Stream<_i2.ReliableDataReceived>.empty(),
      ) as _i5.Stream<_i2.ReliableDataReceived>);

  @override
  _i5.Future<_i7.TransferResult> sendReliable(
    String? deviceId,
    List<int>? payload,
  ) => (super.noSuchMethod(
    Invocation.method(#sendReliable, [deviceId, payload]),
    returnValue: _i5.Future<_i7.TransferResult>.value(
      _i7.TransferResult.delivered,
    ),
  ) as _i5.Future<_i7.TransferResult>);

  @override
  void pushDiscovery(_i6.DiscoveredOneBitDevice? device) => super.noSuchMethod(
    Invocation.method(#pushDiscovery, [device]),
    returnValueForMissingStub: null,
  );

  @override
  void pushConnectionState(String? deviceId, _i2.BleConnectionState? state) =>
      super.noSuchMethod(
        Invocation.method(#pushConnectionState, [deviceId, state]),
        returnValueForMissingStub: null,
      );

  @override
  void pushCharacteristicChanged({
    required String? deviceId,
    required String? serviceUuid,
    required String? characteristicUuid,
    required List<int>? value,
    bool? isIndication = false,
  }) => super.noSuchMethod(
    Invocation.method(#pushCharacteristicChanged, [], {
      #deviceId: deviceId,
      #serviceUuid: serviceUuid,
      #characteristicUuid: characteristicUuid,
      #value: value,
      #isIndication: isIndication,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.BlePermissionState> requestPermissions() =>
      (super.noSuchMethod(
        Invocation.method(#requestPermissions, []),
        returnValue: _i5.Future<_i2.BlePermissionState>.value(
          _i2.BlePermissionState.granted,
        ),
      ) as _i5.Future<_i2.BlePermissionState>);

  @override
  _i5.Future<_i2.BlePermissionState> recoverPermissions() =>
      (super.noSuchMethod(
        Invocation.method(#recoverPermissions, []),
        returnValue: _i5.Future<_i2.BlePermissionState>.value(
          _i2.BlePermissionState.granted,
        ),
      ) as _i5.Future<_i2.BlePermissionState>);

  @override
  _i5.Future<void> openBluetoothSettings() => (super.noSuchMethod(
    Invocation.method(#openBluetoothSettings, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<String> startAdvertising(_i8.BleAdvertiseConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(#startAdvertising, [config]),
        returnValue: _i5.Future<String>.value(
          _i9.dummyValue<String>(
            this,
            Invocation.method(#startAdvertising, [config]),
          ),
        ),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> stopAdvertising() => (super.noSuchMethod(
    Invocation.method(#stopAdvertising, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<String> startScan(_i2.BleScanConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(#startScan, [config]),
        returnValue: _i5.Future<String>.value(
          _i9.dummyValue<String>(this, Invocation.method(#startScan, [config])),
        ),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> stopScan() => (super.noSuchMethod(
    Invocation.method(#stopScan, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.BleConnectionInfo> connect(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(#connect, [deviceId]),
        returnValue: _i5.Future<_i2.BleConnectionInfo>.value(
          _FakeBleConnectionInfo_1(
            this,
            Invocation.method(#connect, [deviceId]),
          ),
        ),
      ) as _i5.Future<_i2.BleConnectionInfo>);

  @override
  _i5.Future<void> disconnect(String? deviceId) => (super.noSuchMethod(
    Invocation.method(#disconnect, [deviceId]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> discoverServices(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(#discoverServices, [deviceId]),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<List<int>> readCharacteristic(
    String? deviceId,
    String? serviceUuid,
    String? characteristicUuid,
  ) => (super.noSuchMethod(
    Invocation.method(#readCharacteristic, [
      deviceId,
      serviceUuid,
      characteristicUuid,
    ]),
    returnValue: _i5.Future<List<int>>.value(<int>[]),
  ) as _i5.Future<List<int>>);

  @override
  _i5.Future<void> writeCharacteristic(
    String? deviceId,
    String? serviceUuid,
    String? characteristicUuid,
    List<int>? value, {
    bool? withoutResponse = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #writeCharacteristic,
      [deviceId, serviceUuid, characteristicUuid, value],
      {#withoutResponse: withoutResponse},
    ),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setNotify(
    String? deviceId,
    String? serviceUuid,
    String? characteristicUuid,
    bool? enabled,
  ) => (super.noSuchMethod(
    Invocation.method(#setNotify, [
      deviceId,
      serviceUuid,
      characteristicUuid,
      enabled,
    ]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}

/// A class which mocks [IdentityAssociationResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdentityAssociationResolver extends _i1.Mock
    implements _i3.IdentityAssociationResolver {
  MockIdentityAssociationResolver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i3.ResolvedBleDevice> get resolvedStream => (super.noSuchMethod(
    Invocation.getter(#resolvedStream),
    returnValue: _i5.Stream<_i3.ResolvedBleDevice>.empty(),
  ) as _i5.Stream<_i3.ResolvedBleDevice>);

  @override
  int get knownPeerCount =>
      (super.noSuchMethod(Invocation.getter(#knownPeerCount), returnValue: 0)
          as int);

  @override
  Map<String, String> get deviceToPeerId => (super.noSuchMethod(
    Invocation.getter(#deviceToPeerId),
    returnValue: <String, String>{},
  ) as Map<String, String>);

  @override
  _i5.Stream<List<_i10.PeerAssociation>> get associationStream =>
      (super.noSuchMethod(
        Invocation.getter(#associationStream),
        returnValue: _i5.Stream<List<_i10.PeerAssociation>>.empty(),
      ) as _i5.Stream<List<_i10.PeerAssociation>>);

  @override
  List<_i10.PeerAssociation> get associations => (super.noSuchMethod(
    Invocation.getter(#associations),
    returnValue: <_i10.PeerAssociation>[],
  ) as List<_i10.PeerAssociation>);

  @override
  int get associationCount =>
      (super.noSuchMethod(Invocation.getter(#associationCount), returnValue: 0)
          as int);

  @override
  void setLocalIdentity(String? publicKeyHex) => super.noSuchMethod(
    Invocation.method(#setLocalIdentity, [publicKeyHex]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.PeerInfo? lookupPeer(String? publicKeyHex) =>
      (super.noSuchMethod(Invocation.method(#lookupPeer, [publicKeyHex]))
          as _i11.PeerInfo?);

  @override
  String? resolveDevice(String? peerIdentityId) =>
      (super.noSuchMethod(Invocation.method(#resolveDevice, [peerIdentityId]))
          as String?);

  @override
  _i10.AssociationConflict? checkConflict(
    String? bleDeviceId,
    String? requestedIdentityId,
  ) => (super.noSuchMethod(
    Invocation.method(#checkConflict, [bleDeviceId, requestedIdentityId]),
  ) as _i10.AssociationConflict?);

  @override
  bool removeAssociation(String? bleDeviceId) => (super.noSuchMethod(
    Invocation.method(#removeAssociation, [bleDeviceId]),
    returnValue: false,
  ) as bool);

  @override
  bool removeAssociationForPeer(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#removeAssociationForPeer, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  void clearAssociations() => super.noSuchMethod(
    Invocation.method(#clearAssociations, []),
    returnValueForMissingStub: null,
  );

  @override
  int generationFor(String? bleDeviceId) => (super.noSuchMethod(
    Invocation.method(#generationFor, [bleDeviceId]),
    returnValue: 0,
  ) as int);

  @override
  _i3.ResolvedBleDevice resolve(_i6.DiscoveredOneBitDevice? device) =>
      (super.noSuchMethod(
        Invocation.method(#resolve, [device]),
        returnValue: _FakeResolvedBleDevice_2(
          this,
          Invocation.method(#resolve, [device]),
        ),
      ) as _i3.ResolvedBleDevice);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PeerRegistryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerRegistryService extends _i1.Mock
    implements _i12.PeerRegistryService {
  MockPeerRegistryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i13.PeerEntry>> get peerStream => (super.noSuchMethod(
    Invocation.getter(#peerStream),
    returnValue: _i5.Stream<List<_i13.PeerEntry>>.empty(),
  ) as _i5.Stream<List<_i13.PeerEntry>>);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  _i13.PeerEntry? get(String? identityId) =>
      (super.noSuchMethod(Invocation.method(#get, [identityId]))
          as _i13.PeerEntry?);

  @override
  bool contains(String? identityId) => (super.noSuchMethod(
    Invocation.method(#contains, [identityId]),
    returnValue: false,
  ) as bool);

  @override
  List<_i13.PeerEntry> getAll() => (super.noSuchMethod(
    Invocation.method(#getAll, []),
    returnValue: <_i13.PeerEntry>[],
  ) as List<_i13.PeerEntry>);

  @override
  void upsert(_i13.PeerEntry? entry) => super.noSuchMethod(
    Invocation.method(#upsert, [entry]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(String? identityId) => super.noSuchMethod(
    Invocation.method(#remove, [identityId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFromIdentities(List<_i11.PeerInfo>? idList) => super.noSuchMethod(
    Invocation.method(#updateFromIdentities, [idList]),
    returnValueForMissingStub: null,
  );

  @override
  void updateConnection(
    String? identityId, {
    required _i2.BleConnectionState? connectionState,
    String? bleDeviceId,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateConnection,
      [identityId],
      {#connectionState: connectionState, #bleDeviceId: bleDeviceId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void updateLifecycle(
    String? identityId, {
    required _i14.PeerLifecycleState? lifecycleState,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateLifecycle,
      [identityId],
      {#lifecycleState: lifecycleState},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void updateTrust(
    String? identityId, {
    required _i15.TrustState? trustState,
    bool? isVerified = false,
    bool? isAuthenticated = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateTrust,
      [identityId],
      {
        #trustState: trustState,
        #isVerified: isVerified,
        #isAuthenticated: isAuthenticated,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
