// Mocks generated by Mockito from annotations
// in onebit/test/peer_reachability_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:onebit/features/ble/ble_state.dart' as _i7;
import 'package:onebit/features/identity/identity_models.dart' as _i6;
import 'package:onebit/features/peer_registry/peer_association.dart' as _i11;
import 'package:onebit/features/peer_registry/peer_connection_manager.dart'
    as _i10;
import 'package:onebit/features/peer_registry/peer_entry.dart' as _i5;
import 'package:onebit/features/peer_registry/peer_lifecycle_state.dart' as _i8;
import 'package:onebit/features/peer_registry/peer_registry.dart' as _i3;
import 'package:onebit/features/routing/neighbor_entry.dart' as _i13;
import 'package:onebit/features/routing/neighbor_table.dart' as _i12;
import 'package:onebit/features/routing/topology.dart' as _i2;
import 'package:onebit/features/trust/trust_state.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTopologySnapshot_0 extends _i1.SmartFake
    implements _i2.TopologySnapshot {
  _FakeTopologySnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PeerRegistryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerRegistryService extends _i1.Mock
    implements _i3.PeerRegistryService {
  MockPeerRegistryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.PeerEntry>> get peerStream => (super.noSuchMethod(
    Invocation.getter(#peerStream),
    returnValue: _i4.Stream<List<_i5.PeerEntry>>.empty(),
  ) as _i4.Stream<List<_i5.PeerEntry>>);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  _i5.PeerEntry? get(String? identityId) =>
      (super.noSuchMethod(Invocation.method(#get, [identityId]))
          as _i5.PeerEntry?);

  @override
  bool contains(String? identityId) => (super.noSuchMethod(
    Invocation.method(#contains, [identityId]),
    returnValue: false,
  ) as bool);

  @override
  List<_i5.PeerEntry> getAll() => (super.noSuchMethod(
    Invocation.method(#getAll, []),
    returnValue: <_i5.PeerEntry>[],
  ) as List<_i5.PeerEntry>);

  @override
  void upsert(_i5.PeerEntry? entry) => super.noSuchMethod(
    Invocation.method(#upsert, [entry]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(String? identityId) => super.noSuchMethod(
    Invocation.method(#remove, [identityId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFromIdentities(List<_i6.PeerInfo>? idList) => super.noSuchMethod(
    Invocation.method(#updateFromIdentities, [idList]),
    returnValueForMissingStub: null,
  );

  @override
  void updateConnection(
    String? identityId, {
    required _i7.BleConnectionState? connectionState,
    String? bleDeviceId,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateConnection,
      [identityId],
      {#connectionState: connectionState, #bleDeviceId: bleDeviceId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void updateLifecycle(
    String? identityId, {
    required _i8.PeerLifecycleState? lifecycleState,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateLifecycle,
      [identityId],
      {#lifecycleState: lifecycleState},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void updateTrust(
    String? identityId, {
    required _i9.TrustState? trustState,
    bool? isVerified = false,
    bool? isAuthenticated = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #updateTrust,
      [identityId],
      {
        #trustState: trustState,
        #isVerified: isVerified,
        #isAuthenticated: isAuthenticated,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PeerConnectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerConnectionManager extends _i1.Mock
    implements _i10.PeerConnectionManager {
  MockPeerConnectionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i10.PeerConnectionRecord>> get connectionStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStream),
        returnValue: _i4.Stream<List<_i10.PeerConnectionRecord>>.empty(),
      ) as _i4.Stream<List<_i10.PeerConnectionRecord>>);

  @override
  List<_i10.PeerConnectionRecord> get connections => (super.noSuchMethod(
    Invocation.getter(#connections),
    returnValue: <_i10.PeerConnectionRecord>[],
  ) as List<_i10.PeerConnectionRecord>);

  @override
  int get connectedPeerCount => (super.noSuchMethod(
    Invocation.getter(#connectedPeerCount),
    returnValue: 0,
  ) as int);

  @override
  bool get hasActiveConnections => (super.noSuchMethod(
    Invocation.getter(#hasActiveConnections),
    returnValue: false,
  ) as bool);

  @override
  List<_i11.PeerAssociation> get currentAssociations => (super.noSuchMethod(
    Invocation.getter(#currentAssociations),
    returnValue: <_i11.PeerAssociation>[],
  ) as List<_i11.PeerAssociation>);

  @override
  int get trackedPeerCount =>
      (super.noSuchMethod(Invocation.getter(#trackedPeerCount), returnValue: 0)
          as int);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String?> connectToPeer(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#connectToPeer, [peerIdentityId]),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> disconnectFromPeer(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#disconnectFromPeer, [peerIdentityId]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i8.PeerLifecycleState lifecycleStateFor(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#lifecycleStateFor, [peerIdentityId]),
        returnValue: _i8.PeerLifecycleState.unknown,
      ) as _i8.PeerLifecycleState);

  @override
  String? deviceForPeer(String? peerIdentityId) =>
      (super.noSuchMethod(Invocation.method(#deviceForPeer, [peerIdentityId]))
          as String?);

  @override
  bool isPeerConnected(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#isPeerConnected, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  _i4.Future<void> disconnectAll() => (super.noSuchMethod(
    Invocation.method(#disconnectAll, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NeighborTable].
///
/// See the documentation for Mockito's code generation for more information.
class MockNeighborTable extends _i1.Mock implements _i12.NeighborTable {
  MockNeighborTable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i13.NeighborEntry>> get neighborStream =>
      (super.noSuchMethod(
        Invocation.getter(#neighborStream),
        returnValue: _i4.Stream<List<_i13.NeighborEntry>>.empty(),
      ) as _i4.Stream<List<_i13.NeighborEntry>>);

  @override
  List<_i13.NeighborEntry> get neighbors => (super.noSuchMethod(
    Invocation.getter(#neighbors),
    returnValue: <_i13.NeighborEntry>[],
  ) as List<_i13.NeighborEntry>);

  @override
  List<_i13.NeighborEntry> get allEntries => (super.noSuchMethod(
    Invocation.getter(#allEntries),
    returnValue: <_i13.NeighborEntry>[],
  ) as List<_i13.NeighborEntry>);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  bool get hasNeighbors =>
      (super.noSuchMethod(Invocation.getter(#hasNeighbors), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  Set<String> get neighborPeerIds => (super.noSuchMethod(
    Invocation.getter(#neighborPeerIds),
    returnValue: <String>{},
  ) as Set<String>);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.NeighborEntry? getNeighbor(String? peerId) =>
      (super.noSuchMethod(Invocation.method(#getNeighbor, [peerId]))
          as _i13.NeighborEntry?);

  @override
  bool isNeighbor(String? peerId) => (super.noSuchMethod(
    Invocation.method(#isNeighbor, [peerId]),
    returnValue: false,
  ) as bool);

  @override
  void addNeighbor(String? peerId, {String? bleDeviceId, int? generation}) =>
      super.noSuchMethod(
        Invocation.method(
          #addNeighbor,
          [peerId],
          {#bleDeviceId: bleDeviceId, #generation: generation},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeNeighbor(String? peerId) => super.noSuchMethod(
    Invocation.method(#removeNeighbor, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeNeighborIfCurrentGeneration(String? peerId, int? generation) =>
      (super.noSuchMethod(
        Invocation.method(#removeNeighborIfCurrentGeneration, [
          peerId,
          generation,
        ]),
        returnValue: false,
      ) as bool);

  @override
  void forceRemoveNeighbor(String? peerId) => super.noSuchMethod(
    Invocation.method(#forceRemoveNeighbor, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.TopologySnapshot buildTopologySnapshot({
    required String? localPeerId,
    String? localDisplayName,
  }) => (super.noSuchMethod(
    Invocation.method(#buildTopologySnapshot, [], {
      #localPeerId: localPeerId,
      #localDisplayName: localDisplayName,
    }),
    returnValue: _FakeTopologySnapshot_0(
      this,
      Invocation.method(#buildTopologySnapshot, [], {
        #localPeerId: localPeerId,
        #localDisplayName: localDisplayName,
      }),
    ),
  ) as _i2.TopologySnapshot);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
