// Mocks generated by Mockito from annotations
// in onebit/test/routing_hardening_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:onebit/features/peer_registry/peer_association.dart' as _i6;
import 'package:onebit/features/peer_registry/peer_connection_manager.dart'
    as _i4;
import 'package:onebit/features/peer_registry/peer_lifecycle_state.dart' as _i7;
import 'package:onebit/features/trust/peer_trust.dart' as _i2;
import 'package:onebit/features/trust/peer_verification.dart' as _i3;
import 'package:onebit/features/trust/trust_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePeerTrust_0 extends _i1.SmartFake implements _i2.PeerTrust {
  _FakePeerTrust_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePeerVerification_1 extends _i1.SmartFake
    implements _i3.PeerVerification {
  _FakePeerVerification_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PeerConnectionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerConnectionManager extends _i1.Mock
    implements _i4.PeerConnectionManager {
  MockPeerConnectionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i4.PeerConnectionRecord>> get connectionStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStream),
        returnValue: _i5.Stream<List<_i4.PeerConnectionRecord>>.empty(),
      ) as _i5.Stream<List<_i4.PeerConnectionRecord>>);

  @override
  List<_i4.PeerConnectionRecord> get connections => (super.noSuchMethod(
    Invocation.getter(#connections),
    returnValue: <_i4.PeerConnectionRecord>[],
  ) as List<_i4.PeerConnectionRecord>);

  @override
  int get connectedPeerCount => (super.noSuchMethod(
    Invocation.getter(#connectedPeerCount),
    returnValue: 0,
  ) as int);

  @override
  bool get hasActiveConnections => (super.noSuchMethod(
    Invocation.getter(#hasActiveConnections),
    returnValue: false,
  ) as bool);

  @override
  List<_i6.PeerAssociation> get currentAssociations => (super.noSuchMethod(
    Invocation.getter(#currentAssociations),
    returnValue: <_i6.PeerAssociation>[],
  ) as List<_i6.PeerAssociation>);

  @override
  int get trackedPeerCount =>
      (super.noSuchMethod(Invocation.getter(#trackedPeerCount), returnValue: 0)
          as int);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String?> connectToPeer(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#connectToPeer, [peerIdentityId]),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> disconnectFromPeer(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#disconnectFromPeer, [peerIdentityId]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i7.PeerLifecycleState lifecycleStateFor(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#lifecycleStateFor, [peerIdentityId]),
        returnValue: _i7.PeerLifecycleState.unknown,
      ) as _i7.PeerLifecycleState);

  @override
  String? deviceForPeer(String? peerIdentityId) =>
      (super.noSuchMethod(Invocation.method(#deviceForPeer, [peerIdentityId]))
          as String?);

  @override
  bool isPeerConnected(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#isPeerConnected, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  _i5.Future<void> disconnectAll() => (super.noSuchMethod(
    Invocation.method(#disconnectAll, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TrustService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrustService extends _i1.Mock implements _i8.TrustService {
  MockTrustService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i8.TrustChangeEvent> get changeStream => (super.noSuchMethod(
    Invocation.getter(#changeStream),
    returnValue: _i5.Stream<_i8.TrustChangeEvent>.empty(),
  ) as _i5.Stream<_i8.TrustChangeEvent>);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  _i2.PeerTrust getTrust(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#getTrust, [peerIdentityId]),
    returnValue: _FakePeerTrust_0(
      this,
      Invocation.method(#getTrust, [peerIdentityId]),
    ),
  ) as _i2.PeerTrust);

  @override
  bool isTrusted(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#isTrusted, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  bool canCommunicate(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#canCommunicate, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  _i2.PeerTrust verify({
    required String? peerIdentityId,
    required DateTime? at,
    required _i2.VerificationMethod? method,
  }) => (super.noSuchMethod(
    Invocation.method(#verify, [], {
      #peerIdentityId: peerIdentityId,
      #at: at,
      #method: method,
    }),
    returnValue: _FakePeerTrust_0(
      this,
      Invocation.method(#verify, [], {
        #peerIdentityId: peerIdentityId,
        #at: at,
        #method: method,
      }),
    ),
  ) as _i2.PeerTrust);

  @override
  _i2.PeerTrust trust({
    required String? peerIdentityId,
    required DateTime? at,
  }) => (super.noSuchMethod(
    Invocation.method(#trust, [], {#peerIdentityId: peerIdentityId, #at: at}),
    returnValue: _FakePeerTrust_0(
      this,
      Invocation.method(#trust, [], {#peerIdentityId: peerIdentityId, #at: at}),
    ),
  ) as _i2.PeerTrust);

  @override
  _i2.PeerTrust revoke({
    required String? peerIdentityId,
    required DateTime? at,
    String? reason,
  }) => (super.noSuchMethod(
    Invocation.method(#revoke, [], {
      #peerIdentityId: peerIdentityId,
      #at: at,
      #reason: reason,
    }),
    returnValue: _FakePeerTrust_0(
      this,
      Invocation.method(#revoke, [], {
        #peerIdentityId: peerIdentityId,
        #at: at,
        #reason: reason,
      }),
    ),
  ) as _i2.PeerTrust);

  @override
  _i2.PeerTrust revokeTrust({
    required String? peerIdentityId,
    required DateTime? at,
    String? reason,
  }) => (super.noSuchMethod(
    Invocation.method(#revokeTrust, [], {
      #peerIdentityId: peerIdentityId,
      #at: at,
      #reason: reason,
    }),
    returnValue: _FakePeerTrust_0(
      this,
      Invocation.method(#revokeTrust, [], {
        #peerIdentityId: peerIdentityId,
        #at: at,
        #reason: reason,
      }),
    ),
  ) as _i2.PeerTrust);

  @override
  List<_i2.PeerTrust> getAll() => (super.noSuchMethod(
    Invocation.method(#getAll, []),
    returnValue: <_i2.PeerTrust>[],
  ) as List<_i2.PeerTrust>);

  @override
  List<_i2.PeerTrust> getTrusted() => (super.noSuchMethod(
    Invocation.method(#getTrusted, []),
    returnValue: <_i2.PeerTrust>[],
  ) as List<_i2.PeerTrust>);

  @override
  List<_i2.PeerTrust> getVerified() => (super.noSuchMethod(
    Invocation.method(#getVerified, []),
    returnValue: <_i2.PeerTrust>[],
  ) as List<_i2.PeerTrust>);

  @override
  List<_i2.PeerTrust> getRevoked() => (super.noSuchMethod(
    Invocation.method(#getRevoked, []),
    returnValue: <_i2.PeerTrust>[],
  ) as List<_i2.PeerTrust>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.PeerVerification getVerification(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#getVerification, [peerIdentityId]),
        returnValue: _FakePeerVerification_1(
          this,
          Invocation.method(#getVerification, [peerIdentityId]),
        ),
      ) as _i3.PeerVerification);

  @override
  bool isVerified(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#isVerified, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  _i3.PeerVerification requireVerification(String? peerIdentityId) =>
      (super.noSuchMethod(
        Invocation.method(#requireVerification, [peerIdentityId]),
        returnValue: _FakePeerVerification_1(
          this,
          Invocation.method(#requireVerification, [peerIdentityId]),
        ),
      ) as _i3.PeerVerification);

  @override
  _i3.PeerVerification verifyIdentity({
    required String? peerIdentityId,
    required DateTime? at,
    required String? publicKeyHex,
    required _i2.VerificationMethod? method,
  }) => (super.noSuchMethod(
    Invocation.method(#verifyIdentity, [], {
      #peerIdentityId: peerIdentityId,
      #at: at,
      #publicKeyHex: publicKeyHex,
      #method: method,
    }),
    returnValue: _FakePeerVerification_1(
      this,
      Invocation.method(#verifyIdentity, [], {
        #peerIdentityId: peerIdentityId,
        #at: at,
        #publicKeyHex: publicKeyHex,
        #method: method,
      }),
    ),
  ) as _i3.PeerVerification);

  @override
  _i2.PeerTrust markAuthenticated({required String? peerIdentityId}) =>
      (super.noSuchMethod(
        Invocation.method(#markAuthenticated, [], {
          #peerIdentityId: peerIdentityId,
        }),
        returnValue: _FakePeerTrust_0(
          this,
          Invocation.method(#markAuthenticated, [], {
            #peerIdentityId: peerIdentityId,
          }),
        ),
      ) as _i2.PeerTrust);

  @override
  bool isAuthenticated(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#isAuthenticated, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  bool canEstablishTrust(String? peerIdentityId) => (super.noSuchMethod(
    Invocation.method(#canEstablishTrust, [peerIdentityId]),
    returnValue: false,
  ) as bool);

  @override
  _i2.PeerTrust establishTrust({
    required String? peerIdentityId,
    required DateTime? at,
  }) => (super.noSuchMethod(
    Invocation.method(#establishTrust, [], {
      #peerIdentityId: peerIdentityId,
      #at: at,
    }),
    returnValue: _FakePeerTrust_0(
      this,
      Invocation.method(#establishTrust, [], {
        #peerIdentityId: peerIdentityId,
        #at: at,
      }),
    ),
  ) as _i2.PeerTrust);
}
