// Mocks generated by Mockito from annotations
// in onebit/test/topology_exchange_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:onebit/features/routing/neighbor_entry.dart' as _i5;
import 'package:onebit/features/routing/neighbor_table.dart' as _i3;
import 'package:onebit/features/routing/peer_reachability.dart' as _i6;
import 'package:onebit/features/routing/reachability_reason.dart' as _i7;
import 'package:onebit/features/routing/topology.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTopologySnapshot_0 extends _i1.SmartFake
    implements _i2.TopologySnapshot {
  _FakeTopologySnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NeighborTable].
///
/// See the documentation for Mockito's code generation for more information.
class MockNeighborTable extends _i1.Mock implements _i3.NeighborTable {
  MockNeighborTable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.NeighborEntry>> get neighborStream => (super.noSuchMethod(
    Invocation.getter(#neighborStream),
    returnValue: _i4.Stream<List<_i5.NeighborEntry>>.empty(),
  ) as _i4.Stream<List<_i5.NeighborEntry>>);

  @override
  List<_i5.NeighborEntry> get neighbors => (super.noSuchMethod(
    Invocation.getter(#neighbors),
    returnValue: <_i5.NeighborEntry>[],
  ) as List<_i5.NeighborEntry>);

  @override
  List<_i5.NeighborEntry> get allEntries => (super.noSuchMethod(
    Invocation.getter(#allEntries),
    returnValue: <_i5.NeighborEntry>[],
  ) as List<_i5.NeighborEntry>);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  bool get hasNeighbors =>
      (super.noSuchMethod(Invocation.getter(#hasNeighbors), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  Set<String> get neighborPeerIds => (super.noSuchMethod(
    Invocation.getter(#neighborPeerIds),
    returnValue: <String>{},
  ) as Set<String>);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.NeighborEntry? getNeighbor(String? peerId) =>
      (super.noSuchMethod(Invocation.method(#getNeighbor, [peerId]))
          as _i5.NeighborEntry?);

  @override
  bool isNeighbor(String? peerId) => (super.noSuchMethod(
    Invocation.method(#isNeighbor, [peerId]),
    returnValue: false,
  ) as bool);

  @override
  void addNeighbor(String? peerId, {String? bleDeviceId, int? generation}) =>
      super.noSuchMethod(
        Invocation.method(
          #addNeighbor,
          [peerId],
          {#bleDeviceId: bleDeviceId, #generation: generation},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeNeighbor(String? peerId) => super.noSuchMethod(
    Invocation.method(#removeNeighbor, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeNeighborIfCurrentGeneration(String? peerId, int? generation) =>
      (super.noSuchMethod(
        Invocation.method(#removeNeighborIfCurrentGeneration, [
          peerId,
          generation,
        ]),
        returnValue: false,
      ) as bool);

  @override
  void forceRemoveNeighbor(String? peerId) => super.noSuchMethod(
    Invocation.method(#forceRemoveNeighbor, [peerId]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.TopologySnapshot buildTopologySnapshot({
    required String? localPeerId,
    String? localDisplayName,
  }) => (super.noSuchMethod(
    Invocation.method(#buildTopologySnapshot, [], {
      #localPeerId: localPeerId,
      #localDisplayName: localDisplayName,
    }),
    returnValue: _FakeTopologySnapshot_0(
      this,
      Invocation.method(#buildTopologySnapshot, [], {
        #localPeerId: localPeerId,
        #localDisplayName: localDisplayName,
      }),
    ),
  ) as _i2.TopologySnapshot);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PeerReachability].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerReachability extends _i1.Mock implements _i6.PeerReachability {
  MockPeerReachability() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get reachableCount =>
      (super.noSuchMethod(Invocation.getter(#reachableCount), returnValue: 0)
          as int);

  @override
  bool get hasReachablePeers => (super.noSuchMethod(
    Invocation.getter(#hasReachablePeers),
    returnValue: false,
  ) as bool);

  @override
  bool isReachable(String? peerId) => (super.noSuchMethod(
    Invocation.method(#isReachable, [peerId]),
    returnValue: false,
  ) as bool);

  @override
  _i7.ReachabilityReason getReachability(String? peerId) => (super.noSuchMethod(
    Invocation.method(#getReachability, [peerId]),
    returnValue: _i7.ReachabilityReason.reachable,
  ) as _i7.ReachabilityReason);

  @override
  List<String> getReachableNeighbors() => (super.noSuchMethod(
    Invocation.method(#getReachableNeighbors, []),
    returnValue: <String>[],
  ) as List<String>);
}
